import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { MobileSidebar } from "@/components/MobileSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex items-start justify-between antialiased`}>
        <div className="md:hidden w-full fixed top-0 py-4 px-4 flex justify-between items-center bg-primary">
          <h1 className="font-bold text-lg">Streamify</h1>
          <MobileSidebar />
        </div>
        <div className="hidden md:flex min-w-[300px] border-r border-neutral-600 min-h-screen">
          <Sidebar />
        </div>
        <main className="w-full h-full p-4">{children}</main>
      </body>
    </html>
  );
}
